wolfcw/libfaketime

src/Makefile
Currently libfaketimeMT.o is compiled without `--DPTHREAD -DPTHREAD_SINGLETHREADED_TIME` .
The patch fixes the `Makefile` to refer to the correct object file name.
With the fix indeed the MT file is built with those directives defined (third `cc` invocation in the output):
```
$ make
cc -o libfaketime.o -c -std=gnu99 -Wall -Wextra -Werror -DFAKE_STAT -DFAKE_SLEEP -DFAKE_TIMERS -DFAKE_INTERNAL_CALLS -fPIC -DPREFIX='"'/usr/local'"' -DLIBDIRNAME='"'/lib/faketime'"'  libfaketime.c
cc -o libfaketime.so.1 -Wl,-soname,libfaketime.so.1 -Wl,--version-script=libfaketime.map -lpthread -shared libfaketime.o -ldl -lm -lrt
cc -o libfaketimeMT.o -c -std=gnu99 -Wall -Wextra -Werror -DFAKE_STAT -DFAKE_SLEEP -DFAKE_TIMERS -DFAKE_INTERNAL_CALLS -fPIC -DPREFIX='"'/usr/local'"' …
```
=> Fix libfaketimeMT build to define PTHREAD

test/timetest.c
On x32, time_t is 64-bit to avoid Y2038 problems.  This doesn't play well
using printf("%ld"), and -Werror turns this into a build failure.
=> Fix build failure on x32 (printf warnings).

src/libfaketime.c
Having the same value/define for coarse and non-coarse clock
leads to duplicate case values in switches.
```
libfaketime.c:2067:16: error: duplicate case value '1'
case CLOCK_REALTIME_COARSE:
libfaketime.c:93:31: note: expanded from macro 'CLOCK_REALTIME_COARSE'
#define CLOCK_REALTIME_COARSE CLOCK_REALTIME
```
=> Fixed coarse clock on platforms that don't support them

src/libfaketime.c
Some libc functions called by ftpl_init() might call fstat() or a similar
function which is intercepted by libfaketime. In this case, the time should
not be faked because the static variables are not yet set up properly.
See https://github.com/wolfcw/libfaketime/issues/72 for further information.
=> Do not fake times during ftpl_init()

src/faketime.c
Replace multiple calls to printf with one single call, passing the entire string at once.
I think this is faster and more readable.
=> Call printf only once in usage(char*)

src/libfaketime.c
Using strtok_r directly on environment string changes the environment
e.g. for subprocesses and thus changes the FAKETIME_ONLY_CMDS
setting for the subprocess to the first command only.
Avoid this by copying the environment string before parsing.
=> do not destroy environment when parsing FAKETIME_ONLY_CMDS

src/Makefile
We rely on the provided local library definitions for the hooked
functions which in some cases (GCC >6) carry a non-null-attribute flag
which causes compile errors on `!= NULL` checks.
=> Disable the non-null compare warning/error.

README
Hi,
Wanted to let you know I've been able to use this library successfully with java applications when setting the DONT_FAKE_MONOTONIC argument.  Without it, the java app hangs.
What do you think?
=> Mention possibility of running java in README

src/Makefile, src/libfaketime.c, src/libfaketime.map, src/uthash.h, test/Makefile, test/test.sh, test/test_OSX.sh, test/timetest.c
pthread_cond_timedwait takes an absolute time as an argument, which it directly passes on to the kernel via the futex syscall. In an application this absolute time argument is calculated via the fake times provided by libfaketime. Since the kernel has no knowledge of the fake time, this currently leads to an erroneous behavior when an application uses pthread_cond_timedwait.
This pull request redefines pthread_cond_timedwait such that it converts the fake time back to real time before passing it on.
Furthermore, a couple of cleanups, which I have noticed while implementing this fix, are included.
Fixes: #85 
In addition this should also fix the performance problems with java applications running on the jvm.
=> Implement fix for pthread_cond_timedwait

src/libfaketime.c
In https://bugs.debian.org/890813, Michael Cree <mcree@orcon.net.nz>
reports:
>  The faketime package fails to work correctly on the Alpha
>  architecture. This failure of faketime to work correctly is the
>  reason for the mbedtls FTBFS, which uses faketime in its test
>  suite [1].
>
>  Consider the following test program (which I call "time-test"):
>
>  #include <stdio.h>
>  #include <sys/time.h>
>  #include <unistd.h>
>
>  int main(void)
>  {
>      struct timeval tv;
>
>      for (int j=0; j<5; j++) {
>          usleep(10000);
>          gettimeofday(&tv, NULL);
>          printf("s=%ld    us=%ld\n", tv.tv_sec, tv.tv_usec);
>      }
>      return 0;
>  }
>
>  When run it produces output like:
>
>  s=1519025990    us=838219
>  s=1519025990    us=848965
>  s=1519025990    us=859711
> …
=> fix gettimeofday() on alpha (see https://bugs.debian.org/890813)

src/Makefile
CPPFLAGS is traditionally used to include C preprocessor flags.  While
faketime doesn't apply anything to CPPFLAGS directly, it is good form
to adopt standard settings that might be externally applied.
=> Use CPPFLAGS during compilation

src/libfaketime.c
The problem is that if we `pthread_cond_timedwait`, then change the timestamp file, the process will get stuck because it has no way to notice that the time has changed and we have no way to prod it awake from the outside.
(The proper solution would be running a watcher thread for the file from libfaketime, but that's a lot of effort.)
This did not used to be a problem because pthread_cond_timedwait would effectively busyloop (since it'd pass a time far in the past.) Since this function was fixed, this problem has been exposed.
The pull request adds a workaround FAKETIME_WAIT_MS variable that forces `pthread_cond_timedwait` to instead wait that many milliseconds, implementing a busyloop. Since `pthread_cond_timedwait` is permitted to wake up whenever and for whatever reason, this is still …
=> Add FAKETIME_WAIT_MS to force pthread_cond_timedwait to wait x ms instead of what its parameters say.

README, src/faketime.c, src/libfaketime.c, test/functests/test_exclude_mono.sh
All other environment variables used by libfaketime start with `FAKETIME_`, why not this one?
The old variable still works, but is no longer mentioned in the README.
=> Rename DONT_FAKE_MONOTONIC to FAKETIME_DONT_FAKE_MONOTONIC for consistency

src/libfaketime.c
I faced with the very confusing issue of the library. Because cache takes time from the input parameter instead of checking the real system time, it is enough to have one stats call for a file with dates from the future to break cache invalidation completely. So I propose not to rely on input parameters as sources of system time.
=> fixed configuration reload

src/libfaketime.c
Building without FAKE_STAT defined causes compilation errors due to
unused variable user_per_tick_inc_set_backup.  Move declaration inside
FAKE_STAT section along with the code making use of it.
=> Wrap user_per_tick_inc_set_backup declaration in ifdef

src/time_ops.h
In 32 bit platforms, overflow occurs during timespec multiplication in macro function `timespecmul2()`.
In this function, `long` value which represent time in seconds is multiplied with large number `1E9` to convert it to nano seconds, this value is not able to fit in 4 byte memory.
Size of `long` type in 32 bit platform is 4 bytes. This is not problem in 64 bit platforms as the size of `long` type in 64 bit platform is 8 bytes. 
For quick verification: https://godbolt.org/z/WTwfWj
Fix suggested is to use `int64_t` for the multiplication result.
=> timespec multiplication overflow fix

src/libfaketime.c
We have a use-case in which we need to change the `FAKETIME_DONT_FAKE_MONOTONIC` setting at runtime. The below change refreshes the setting from the envar when the setting cache expires.
=> Refresh the monotonic faketime setting envar when cache expires.

src/libfaketime.c
The real `clock_gettime` doesn't use much stackspace. Allocating large stack buffers may cause breakage when `fake_clock_gettime` is called in threads that have been started with a small amount of stackspace. (This problem was found when using faketime with D's background GC threads, which set the stacksize to 16KB.)
=> fake_clock_gettime: avoid placing large buffers on the stack

src/libfaketime.c
Three problems were found and fixed:
- `sigprocmask` is the wrong function; technically, only `pthread_sigmask` is allowed in multithreaded programs. (They're aliases, but it's the principle of the thing.)
- In some cases, due to early return from `fake_clock_gettime`, the faketime lock was not released. Return is now handled by a goto. (I'm sorry, this was the only way I could think of.)
- I fucked up: my previous pull request was assigning to the global lock state struct before we actually had the lock. This is naturally a bad idea, and was causing hangs in practice as we restored the wrong process mask. Also fixed. Mea culpa.
=> Fix timing issue with multiple threads

NEWS, README, src/libfaketime.c
When the environment variable FAKETIME_TIMESTAMP_FILE is set, points to
a writeable (creatable) custom config file and the environment variable
FAKETIME_UPDATE_TIMESTAMP_FILE is "1", then the file also is updated on
each call. By this, a common "virtual time" can be shared by several
processes, where each can adjust the time for all.
=> settime functions support FAKETIME_UPDATE_TIMESTAMP_FILE (for #239).

test/timetest.c
On Ubuntu 20.04 using gcc 9.3, make test fails due to a deprecated
function (ftime) warning in combination with -Werror in timetest.c.
Since the warning is from a test testing that the deprecated function
can be replaced using LD_PRELOAD, I think it's reasonable to just
silence the warning in that case.
```
gcc -c -std=gnu99 -Wall -DFAKE_STAT -Werror -Wextra  timetest.c
timetest.c: In function ‘main’:
timetest.c:219:5: error: ‘ftime’ is deprecated [-Werror=deprecated-declarations]
219 |     ftime(&tb);
|     ^~~~~
In file included from timetest.c:26:
/usr/include/x86_64-linux-gnu/sys/timeb.h:39:12: note: declared here
39 | extern int ftime (struct timeb *__timebuf)
|            ^~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:12: timetest.o] Error 1
```
```
$ cc …
```
=> Fix make test build failure on gcc 9.3

src/Makefile, src/libfaketime.c
- Fix the utime() and utimes() functions to work with a NULL arg  (which is a request for "now").
- Add missing utimensat() & futimens() functions.
- Add support for a FAKE_UTIME define and enable it by default.  This is like defining FAKE_FILE_TIMESTAMPS except that the code defaults to NO utime faking unless FAKE_UTIME environment var enables it.
- When utime values are not being faked, the use of a NULL arg or a UTIME_NOW nsec value gives the user NOW translated into their fake current time.  This is because the caller's fake times are otherwise being preserved, so we should help their NOW request also be handled as a fake time.
- Mention FAKE_FILE_TIMESTAMPS & FAKE_UTIME in the src/Makefile.
- Move a sanity check in fake_clock_gettime() to where it is actually prior to all the pointer …
=> Some fixes and improvements for utime functions.

src/faketime.c
While debugging an issue I experienced similar to #143, it was really confusing that faketime printed error messages without identifying that they were from the faketime wrapper.
Add a prefix to indicate that the error messages are coming from faketime, just like libfaketime does.
=> faketime: Prefix error messages with faketime

src/libfaketime.c
Without this fix, when compiling with `-O1` or more, we see:
```
libfaketime.c: In function ‘fake_clock_gettime’:
libfaketime.c:2843:7: error: variable ‘ret’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
2843 |   int ret = INT_MAX;
|       ^~~
cc1: all warnings being treated as errors
```
This error doesn't happen when using `-O0`.
The warning appears to happen when the compiler optimizes `ret`
because it is the return value for the function call (meaning maybe
preserved in a register, or some other more risky placement that might
break during the `goto` error cases?).  Explicitly marking it as
volatile should keep the compiler from optimizing that way, regardless
of the level of optimization the user asks for.
I got the idea to use `volatile` here from the rather …
=> Try to fix warning about clobbering under optimization (Closes #284)

.gitignore, test/Makefile, test/getrandom_test.c, test/randomtest.sh
In trying to test the experimental getrandom features, I found a few
minor problems.  These changes should make it easier to test.
After building, the developer can now just do:
make -C test randomtest
This will do a basic verfication that the feature works as expected.
I haven't tried to integrate this with the overall "make test".  To do
that right, it should condition the test on the definition of
FAKE_RANDOM.
=> Ease build of getrandom_test

test/getrandom_test.c, test/randomtest.sh
Previously, we had failed to test code with getrandom() against
LD_PRELOAD when FAKERANDOM_SEED was unset.
We also want to try calling getrandom twice in a single process to
make sure that works OK.
=> Improve tests for FAKE_RANDOM

.gitignore, test/Makefile, test/librandom.c, test/librandom.h, test/randomtest.sh, test/use_lib_random.c
Running "make randomtest" should demonstrates the segfault described
in https://github.com/wolfcw/libfaketime/issues/295
It currently fails for me:
``` console
$ make randomtest
gcc -c -o librandom.o -fpic -std=gnu99 -Wall -DFAKE_STAT -Werror -Wextra  librandom.c
gcc -o librandom.so -shared -std=gnu99 -Wall -DFAKE_STAT -Werror -Wextra  librandom.o
gcc -L. -o use_lib_random -std=gnu99 -Wall -DFAKE_STAT -Werror -Wextra   use_lib_random.c -lrandom
./randomtest.sh
testing shared object with getrandom() in library constructor
getrandom() yielded 0xe5587d15
called func()
now with LD_PRELOAD and FAKERANDOM_SEED
getrandom() yielded 0x00000000
called func()
now with LD_PRELOAD without FAKERANDOM_SEED
Segmentation fault
make: *** [Makefile:29: randomtest] Error 139
$
```
=> test getrandom() in library initialization without FAKERANDOM_SEED

src/libfaketime.c
This avoids potential failure if another library calls getrandom()
within its constructor before we are loaded.
For me, it lets "make randomtest" succeed in tests/
Closes: #295
=> Ensure that real_getrandom is initialized properly

src/Makefile, src/libfaketime.c, test/pidtest.sh
I went with the runtime environment variable being FAKETIME_FAKEPID
since it seems less likely to collide with anything else.
Closes: #297
Note: this is a work in progress, and a proof of concept.  i haven't done any more significant testing, and i suspect it's still vulnerable to failures in library initialization routines when `FAKETIME_FAKEPID` is unset, a la #295.
Just wanted to offer patches for consideration
=> Enable intercepting getpid()

.gitignore, test/Makefile, test/libgetpid.c, test/libgetpid.h, test/pidtest.sh, test/use_lib_getpid.c
This tries to address concerns raised in #295 and #297 about getpid and ill-timed calls from other library constructors.  (there's an additional minor fix for the `getrandom` test of the same situation as well)
=> Test getpid() against a library that invokes getpid() in its constructor

src/Makefile, src/libfaketime.c, test/Makefile, test/syscall_test.c, test/syscalltest.sh
This is an attempt at an implementation to address #301.
Some things worth noting:
- I am not particularly confident in my reverse of the variadic C
ABI. While the code appears to work for me on x86_64, I could
imagine some variations between platforms that I'm not
understanding.
- This works to intercept the invocation of syscall as seen in
test/syscalltest.sh, as long as it was compiled with -DFAKE_RANDOM
- defining -DINTERCEPT_SYSCALL on non-Linux platforms should result
in a compile-time error.
- This does *not* work to intercept the syscall sent by `openssl
rand`, for some reason I don't yet understand.  Perhaps openssl has
some platform-specific syscall mechanism that doesn't route them
through libc's syscall() shim?
=> Intercept syscall

src/libfaketime.c
This addresses part of the concerns raised in #297
=> Use real_getpid instead of getpid in ft_shm_create() under FAKE_PID

man/faketime.1, src/faketime.c
I had to decide what to do if FAKE_PID wasn't defined during the
build. I decided that since the wrapper can't be sure it is preloading
the same library that it was built with (someone could somehow mix and
match the library and the wrapper tool), it should just warn and pass
along the value anyway.
This reserves the option space, but shouldn't annoy people too much if
they are running it on a system that doesn't have FAKE_PID enabled.
I note that this happens regardless of whether it is a "direct"
invocation or not.  I don't fully understand all the tradeoffs here,
so I would appreciate another set of eyes reviewing this choice.
Closes: #308
=> faketime: add -p option to wrapper for setting PID

src/libfaketime.c
If FAKERANDOM is unset, we were still intercepting syscall() and
passing it through to clock_gettime, rather than letting it fall
through to real_syscall.
That would have the effect of diverting syscall(__NR_clock_gettime,…)
into the libc invocation of clock_gettime(…) (via real_clock_gettime).
While that probably does the same thing, it's probably a mistake to do
such a diversion when FAKETIME is unset.
=> Pass through syscall(__NR_clock_gettime) if FAKERANDOM is unset

.gitignore, src/Makefile, src/faketime_common.h, src/libfaketime.c, test/Makefile, test/variadic/inner.c, test/variadic/main.c, test/variadic/outer.c
This series adds a test for our assumptions about variadic promotion when `INTERCEPT_SYSCALL` is defined.  It should help to catch future problems like #310
=> Test variadic promotion

man/faketime.1, src/faketime.c
Just as it says on the tin :)
Adds a `--date-prog PATH` switch. (Follows up from testing with issue #315)
While developing this, I added some tracing printouts but left them commented away in the PR submission so as to not pollute the output in a normal wrapped operation. Maybe there should be a switch/envvar for field debugging.
=> faketime.c: allow user to select their implementation of GNU date

src/faketime.c
Following up from issue #315, this PR fixes the default "date_cmd" for SunOS platforms. Since with illumos there are actually many distributions, with various userlands (even some GNU by default, but this is rare), it is probable that `date` is the old SVR5 one without the fancy GNU-`date` capabilities, provided by additional packages delivering a `gdate`.
That said, the high probability is not a 100% guarantee (distros do differ), so having a switch per #317 to help end-users is even better.
=> faketime.c: default to GNU date as "gdate" on Sun-related OSes

man/Makefile
To make libfaketime reproducible don't embed the timestamp in the gzip
header.
Motivation: https://reproducible-builds.org
=> Do not store the timestamp in the gzip

src/Makefile, src/libfaketime.c
(this is based on a sibling pull request, only the last commit is really part of this pull request)
Provide a way to get libfaketime to not initialize a shared memory segment.
For reasons that I didn't dig into, the shared memory setup fails when wrapping something that does a ton of process spawning (a build system). I have patched it out of my build of libfaketime for months as a result, because it's just not needed when simply changing time by a fixed offset, for instance.
This new variable also unsets PTHREAD_SINGLETHREADED_TIME, which is not strictly necessary as that can already be disabled, but this is also a reliability hazard due to potentially creating deadlocks, so I think it makes sense to disable it in this case too.
=> Add a build variable to opt-out of behaviors that reduce reliability

src/libfaketime.c
the newer version gcc warns `this ‘while’ clause does not guard... [-Werror=misleading-indentation]`. looks like the author just omitted the `do` and the `while(0)` counts as a separate statement.
in practice this isn't causing any actual problem now afaict.
=> fix do/while guard for DONT_FAKE_TIME macro

man/faketime.1, src/libfaketime.c
This is a nonsubstantive change, just a few minor formatting and grammar and link fixups.
The biggest visible change is the nroff source for `man/faketime.1`, which is now one sentence per line, a format that is easier to read and simpler to review in a line-by-line diff.
=> formatting cleanups

src/libfaketime.c
strptime(3) doesn't set errno, so when it was failing, calling perror()
meant producing messages like:
Failed to parse FAKETIME timestamp: Success
Rather than use perror(), just send the warning message directly to
stderr.
This was first reported in https://bugs.debian.org/939789
=> Avoid spurious "Success" error message.

src/libfaketime.c
This fixing compiling with `EXTRA_FLAGS=-UFAKE_STAT` 
This also seems to fix a problem where as by default FAKE_UTIME is disabled at compile time, the `fake_utime_disabled` gets set to 0 (enabling it?)
=> fixes #374 fix compiling without FAKE_STAT or with FAKE_UTIME

test/Makefile
When `-DINTERCEPT_SYSCALL` is not set, the test suite currently still tests snippets related to syscall when invoked with `make test_variable_data` from the `test/` directory.  Sorry i missed this before.
This is what was the proximate cause of https://bugs.debian.org/1007828
=> clean up tests related to syscall

src/Makefile, src/libfaketime.c, test/Makefile, test/libmallocintercept.c, test/test.sh
This is my attempt at fixing #365. I cleaned up the proposed patch from there and actually simplified it a bit. I also added a unit test that would previously hang (deadlock in `pthread_mutex_lock()`) and now passes.
As requested, this adds a new define. I chose to call it `FAIL_PRE_INIT_CALLS`. I also had to enable it by default since otherwise the test would hang. I kind of expect this to be an unsatisfactory solutions. Please advice how to properly integrate this test (or whether it should just be deleted).
I *did* test that this makes the hang with both `clang -fsanitize=address main.c` and `clang++ -fsanitize=address main.cpp` go away (where `main.c(pp)` is just an empty main function). I also checked that without this changes, the resulting programs would hang under faketime.
Fixes …
=> Work-around / fix libasan incompatibility

src/libfaketime.c
Without the changes Sun studio 12.8 compiler fails, for example
Note that only the errors are fixed. On the compiler above, some
warnings still remain, so -Werror has to be removed as well from the
compiler switches in order for the compilation to succeed.
=> Refactor to get rid of some non-standard gcc extensions

test/snippets/time.c
Cast t to unsigned long and use the %lu format specifier instead of %zd.
This is more portable to 32-bit arches, avoiding the following compiler
error:
snippets/time.c:2:31: error: format ‘%zd’ expects argument of type ‘signed size_t’, but argument 3 has type ‘time_t’ {aka ‘long int’} [-Werror=format=]
2 | printf("[%s] time() yielded %zd\n", where, t);
|                             ~~^            ~
|                               |            |
|                               int          time_t {aka long int}
|                             %ld
cc1: all warnings being treated as errors
=> test/snippets: fix time.c compiler error on 32-bit arches

src/libfaketime.c
One callsite of `ftpl_init` wasn't protected by the `if (!initialized)` condition, specifically the "constructor" call:
```C
static void ftpl_init (void) __attribute__ ((constructor));
```
If another "constructor" was called before this one, and that other constructor used time or filesystem functions, ftlp_init would be initialized by that other constructor, and then reinitialized by the ftpl_init constructor. At that point, confusion ensues.
=> ensure faketime can't be initialized more than once

src/libfaketime.c
musl removed LFS64 compat[1] so stat64 is no longer defined by default, but we can bring it back for now through _LARGEFILE64_SOURCE
Link: https://www.openwall.com/lists/musl/2022/09/26/1 [1]
Fixes: #446
------
Hi & thanks for libfaketime!
#446 ended up in a low "let's just not use alpine 3.19" note but it's easy enough to keep the build working for now, and it also doesn't seem to break on glibc either (running tests seem happy)
=> fix build on recent musl (stat64 compat)

Makefile, src/Makefile.OSX
Fixes #334
This pull requests adds support for MacOS ARM64, by adding `-target` to the CFLAGS/LDFLAGS.
Without this, the user will receieve the following error:
```sh
dyld[6675]: terminating because inserted dylib '/usr/local/lib/faketime/libfaketime.1.dylib' could not be loaded: tried: '/usr/local/lib/faketime/libfaketime.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/faketime/libfaketime.1.dylib' (no such file), '/usr/local/lib/faketime/libfaketime.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
dyld[6675]: tried: '/usr/local/lib/faketime/libfaketime.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), …
```
=> Check if the user is on ARM64, add target to CFLAGS/LDFLAGS

README, man/faketime.1, src/faketime.c, src/libfaketime.c
The use of shared memory has side effects (triggering `malloc` and causing a deadlock or crash as reported in https://github.com/wolfcw/libfaketime/issues/130#issuecomment-1989773770).
Currently, the only way to opt out of shared memory is by compiling with -DFAKE_STATELESS.
To allow disabling shared memory without recompiling, this patch introduces the --disable-shm option to `faketime`, equivalent to setting the `FAKETIME_DISABLE_SHM=1` environment variable.
=> Add --disable-shm / FAKETIME_DISABLE_SHM

src/libfaketime.c
For a detailed analysis that resulted in this PR, see https://github.com/wolfcw/libfaketime/issues/130#issuecomment-1989773770
With some allocators (e.g. jemalloc), a circular dependency exists between `malloc` and libfaketime. When libfaketime triggers a `malloc` call while the initial `malloc` call is initializing, infinite recursion or a deadlock may occur. One of the causes is a `malloc` call by `dlsym` / `dlvsym`, when the requested symbol cannot be resolved. To avoid triggering this condition, this patch introduces a way to avoid `dlsym` / `dlvsym` calls under these conditions.
The feature consists of two environment variables:
First, launch `faketime` with the `FAKETIME_DEBUG_DLSYM=1` environment variable to identify the non-resolving symbols:
```
$ FAKETIME_DEBUG_DLSYM=1 faketime …
```
=> Add FAKETIME_IGNORE_SYMBOLS to skip unneeded dlsym

src/libfaketime.c
The shared semaphore is closed but it's not assigned to null. That's required because the logic check the semaphore status if it's not null. For this reason, we are getting a core some times.
=> Preventing shared semaphore to be used again

test/libmallocintercept.c
We should ignore the return value for logging function, to fix a new gcc ftbfs libmallocintercept.c: In function ‘print_msg’:
libmallocintercept.c:27:9: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
27 |         write(0, msg, strlen(msg));
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~
=> test/libmallocintercept.c: fix write function unused return value

src/libfaketime.c
Fixes
https://github.com/wolfcw/libfaketime/issues/483
We saw this in Debian CI: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1093412#35
=> Re-disable faking utime by default

src/libfaketime.c, test/Makefile
Hi.  This is an attempt at fixing #418.
The background is that faketime is used quite extensively in Debian, as part of various packages' tests.  Most 32-bit architectures in Debian are now using 64-bit time_t, \[1] and the lack of support in faketime broke those tests.
\[1] The main exception is i386 (aka x86_32) which is still using 32-bit time_t, because the principal use case for that arch is running old proprietary binaries, which obviously can't be updated.
This patch series works in Debian - our CI has confirmed that all the packages which were broken by t64 are now fixed.  (Some race fixes were necessary too - I'm going to make another MR with those.)
Debian is entirely ELF now.  So it is possible that this series won't work on every platform supported by faketime.  Probably, in …
=> Fake 64-bit time on 32-bit systems

src/libfaketime.c
There were several places where the code in `libfaketime.c` used ad-hoc synchronisation (eg for doing the initialisation only once) using non-atomic C variables.  In a multithreaded program, this is not correct.  The C language rules are that data races like this are completely forbidden, and the compiler is allowed to optimise the code using the assumption that such races do not ever occur.
In practice, while trying to fix faketime in Debian trixie, I found that faketime misbehaved in CI, in the test suites of various other packages.  Notably, the Ruby interpreter, but other cases too.  Some cases involved stack traces, and others "impossible" results.  In each case, I examined the output from the test case, and the apparently-relevant code in libfaketime.c.  In each case, I found code …
=> Fix several data races

src/libfaketime.c
build fail with appended flags -DINTERCEPT_SYSCALL -DINTERCEPT_FUTEX noted in #493 
```shell
$ sudo make
make  -C src all
make[1]: Entering directory '/home/piotrbz/libfaketime/src'
cc -o libfaketime.o -c -std=gnu99 -Wall -Wextra -Werror -DFAKE_PTHREAD -DDEBUG -DFAKE_STAT -DFAKE_UTIME -DFAKE_SLEEP -DFAKE_TIMERS -DFAKE_INTERNAL_CALLS -DINTERCEPT_SYSCALL -DINTERCEPT_FUTEX -fPIC -DPREFIX='"'/usr/local'"' -DLIBDIRNAME='"'/lib/faketime'"'  -Wno-nonnull-compare   libfaketime.c
libfaketime.c: In function ‘handle_futex_syscall’:
libfaketime.c:4199:20: error: ‘FUTEX_CLOCK_REALTIME’ undeclared (first use in this function); did you mean ‘CLOCK_REALTIME’?
4199 |     if (futex_op & FUTEX_CLOCK_REALTIME)
|                    ^~~~~~~~~~~~~~~~~~~~
|                    CLOCK_REALTIME …
```
=> missing FUTEX_CLOCK_REALTIME declaration when build with flags -DINTERCEPT_SYSCALL -DINTERCEPT_FUTEX

Makefile, src/Makefile.OSX
There are two/three major issues on release 0.9.11 that broke `libfaketime` on macOS.
- https://github.com/wolfcw/libfaketime/pull/466 actually removed support for `arm64`, which is still very important for older darwin releases not aware of the newer `arm64e` to work, evident in https://github.com/wolfcw/libfaketime/pull/466#issuecomment-2016894510.
- Nitpick: It uses an unnecessary product version whereas it could be as simple as `-arch arm64e`. It adds a confusing error message instead of a proper explanation. It disables the test to fool itself that it is working, but the resulting `.dylib` for `arm64e` is still not functional.
- Why not functional? Apple silently compiled all its system binaries against the new `arm64e` ABI since some months ago, and at the same time forbid …
=> Compile for arm64 on darwin again

src/Makefile.OSX, src/libfaketime.c
Follow up to https://github.com/wolfcw/libfaketime/pull/497, these changes should hopefully un-break darwin. 🤞
Closes https://github.com/wolfcw/libfaketime/issues/498 
```sh
$ /usr/bin/file $(which /bin/date)
/bin/date: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/date (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/date (for architecture arm64e):	Mach-O 64-bit executable arm64e
$ /usr/bin/file $(which date)
/nix/store/d72z8b7fvvcin2p84x7h5s0abkggplzc-coreutils-9.7/bin/date: Mach-O 64-bit executable arm64
$ FAKETIME="2020-12-24 20:30:00" DYLD_INSERT_LIBRARIES=./src/libfaketime.1.dylib /bin/date
Thu 24 Dec 2020 20:30:00 HKT
$ FAKETIME="2020-12-24 20:30:00" …
```
=> Fix darwin and arm64e

src/libfaketime.c
I got the logic wrong in PR #501 in the inner `#ifndef __APPLE__`. This broke building on linux. This should fix it.
=> Fix fake_stat64buf() again

src/libfaketime.c, test/timetest.c
In an application where a thread sets CLOCK_REALTIME with a server time, and another thread uses CLOCK_MONOTONIC for timeouts, it was found that CLOCK_MONOTONIC was being updated as well, thus FAKETIME_DONT_FAKE_MONOTONIC=1 was added when starting the application.
However, it was found that if the thread using CLOCK_MONOTONIC called pthread_cond_timedwait and the other thread set CLOCK_REALTIME, the blocking call would time out early. This is because even though the real CLOCK_MONOTONIC is specified, pthread_cond_timedwait_common was still referencing faketime.
=> Fix MONOTONIC pthread_cond_timedwait when REALTIME is set

src/Makefile.OSX
This PR fixes #506 
It builds arch64 an arch64e separately and then lipo them to the final dylib as proposed by @alebcay
=> fixes issue #506 - build arch64 and arch64e separately

src/libfaketime.c
This fixes missing modification of timestamps in stat() calls for programs built with large file support (-D_FILE_OFFSET_BITS=64), both 32- and 64-bit.
Demo code:
```
$ cat <<EOF >test.c
#include <sys/stat.h>
int main()
{
struct stat buf;
return stat("/", &buf);
}
EOF
```
32-bit build:
```
$ nix-shell -p gcc --argstr system i686-linux
nix-shell$ gcc test.c && ltrace ./a.out
__libc_start_main([ "./a.out" ] <unfinished ...>
stat(0x804a008, 0xffa4b644, 895, 0) = 0
+++ exited (status 0) +++
nix-shell$ gcc -D_FILE_OFFSET_BITS=64 test.c && ltrace ./a.out
__libc_start_main([ "./a.out" ] <unfinished ...>
stat64(0x804a008, 0xffdcf61c, 100, 0xffdcfaeb) = 0
+++ exited (status 0) +++
nix-shell$ file a.out
a.out: ELF 32-bit LSB executable, Intel 80386, [...]
```
64-bit build:
```
$ nix-shell -p gcc …
```
=> Handle stat64() call

src/libfaketime.c
musl defines stat64 as stat, leading to this build error:
```
gcc -o libfaketime.o -c -std=gnu99 -Wall -Wextra -Werror -DFAKE_PTHREAD -DFAKE_STAT -DFAKE_UTIME -DFAKE_SLEEP -DFAKE_TIMERS -DFAKE_INTERNAL_CALLS -fPIC -DPREFIX='"'/nix/store/qpyvvrcas950da98mssw6ixlw7ckvyrb-libfaketime-0.9.11'"' -DLIBDIRNAME='"'/lib'"'  -Wno-nonnull-compare   libfaketime.c
In file included from libfaketime.c:55:
libfaketime.c:1276:5: error: redefinition of ‘stat’
1276 | int stat64 (const char *path, struct stat64 *buf)
|     ^~~~~~
/nix/store/g9cgi4yyn5vrd1f9axj8gxdvwzv5ssvk-musl-1.2.5-dev/include/sys/stat.h:80:5: note: previous definition of ‘stat’ with type ‘int(const char *, struct stat *)’
80 | int stat(const char *__restrict, struct stat *__restrict);
|     ^~~~
make[1]: *** [Makefile:161: libfaketime.o] …
```
=> Only define stat64 when building with glibc
