wolfcw/libfaketime

src/libfaketime.c
This is just a draft, since I didn't fixed all places (but maybe this will be enough).
=> Raw support for COARSE clocks

README, README.developers, man/faketime.1, src/faketime.c
They were found using [mwic](http://jwilk.net/software/mwic).
=> Fix spelling mistakes

src/faketime_common.h
Minor fix to allow builds on OSX (Sierra)
=> Adding some code to make OSX build properly.

src/libfaketime.c
Python's time.sleep() is implemented using select (yes, oldschool unix C guys...)
=> Support select call

NEWS
I've legally changed my name since this time. Fix the docs to indicate the correct name.
=> fix my name

src/libfaketime.c
Signed-off-by: Jon Ringle <jringle@gridpoint.com>
=> Allow specifying fractions of a second when setting FAKETIME

src/libfaketime.c
At the moment I work with complex Java application, and I faced 2 problems:
1. Sometimes threads of Java application stuck
2. Sometimes application crashed with SIGSEGV
After digging into the problem I found a thread safety issue inside pthread faking methods. With this patch, it works for me. Probably it fixes a lot of open issues related to Java.
=> Fixed thread safety issue in pthread faking methods

src/libfaketime.c
Ran into this with D GC background threads (again).
Order of operations:
- D thread calls `clock_gettime`.
- `fake_clock_gettime` grabs lock.
- `fake_clock_gettime` messes around with files, which takes a bit.
- other D thread triggers GC
- GC sends `SIGUSR1` to the first thread to freeze it
- GC waits for background threads to terminate using `pthread_cond_timedwait`.
- faketime `pthread_cond_timedwait` calls `fake_clock_gettime`.
- Deadlock.
To avoid this, block all signals ( https://www.gnu.org/software/libc/manual/html_node/Why-Block.html ) while the lock is held. This way, the thread will only be frozen once the lock has been released again.
=> Fix deadlock issues with signals: block all signals while inside mutex.

src/libfaketime.c
This fixes the `{ 0 }` initializer not compiling on some platforms.
Fix issue #231
Fix issue #235
=> replace global state struct with local state struct holding a pointer to the global mutex variable

README
=> Fix spelling

src/faketime.c
i don't how to help make this kind of boring update happen in a more automated fashion on subsequent version releases, so i'm just providing the direct fix for now.
=> fix embedded version number

.gitignore, src/libfaketime.c, test/Makefile, test/getentropy_test.c, test/randomtest.sh, test/repeat_random.c
This series improves the testing for randomness, introduces a test to confirm that getentropy is also affected, and implements a fix for `getentropy()` itself.
=> better testing for interception of randomness from the kernel, including getentropy()

src/libfaketime.c
It's almost identical to timer_{set,get}time, including the same caveat that it assumes that the clock of the timer is real time.
I've tested this by using libfaketime the way I normally do (wrapping a build), and it worked, including the test that was failing so far because some timers were not firing on time. I also observed timerfd_settime calls using strace, and libfaketime vs not libfaketime were indistinguishable.
(I'll note there's also missing wrappers for {set,get}itimer, which `ping` uses, but I didn't address this. Maybe in the future)
=> add support for timerfd_{set,get}time

src/libfaketime.c
Pretty self-explanatory. This function is in C11, see https://en.cppreference.com/w/c/chrono/timespec_get.
=> wrap timespec_get

src/Makefile
According to whether they are set by default, so it's easier to determine what the default is.
=> Group build variables help in Makefile

test/Makefile
more administrivia.  sorry i didn't catch this earlier!
=> test: remember to clean up repeat_random

src/libfaketime.c
=> Reset shared memory when start time is reset

src/libfaketime.c
=> Handle short reads from timestamp file

src/libfaketime.c
Before vs after on my machine:
```diff
$ LANG=C LD_PRELOAD=src/libfaketime.so.1 FAKETIME=+1d strace -e statx -v stat Makefile |& grep 202
statx(AT_FDCWD, "Makefile", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_blksize=4096, stx_attributes=0, stx_nlink=1, stx_uid=1000, stx_gid=1000, stx_mode=S_IFREG|0664, stx_ino=4326782, stx_size=1006, stx_blocks=8, 
stx_attributes_mask=STATX_ATTR_COMPRESSED|STATX_ATTR_IMMUTABLE|STATX_ATTR_APPEND|STATX_ATTR_NODUMP|STATX_ATTR_ENCRYPTED|STATX_ATTR_AUTOMOUNT|STATX_ATTR_MOUNT_ROOT|STATX_ATTR_VERITY|STATX_ATTR_DAX,
stx_atime={tv_sec=1690764183, tv_nsec=379172976} /* 2023-07-30T20:43:03.379172976-0400 */,
stx_btime={tv_sec=1617121640, tv_nsec=172041510} /* 2021-03-30T12:27:20.172041510-0400 */, …
```
=> adding support for faking statx

src/Makefile
Add compiler specific options based on detected compiler gcc/clang
=> Makefile: Detect compiler in makefile

src/libfaketime.c
Some operations may directly use futex + timeout. For example, in `libcstdc++`, "std::__atomic_futex_unsigned_base::_M_futex_wait_until_steady" is used to pass in a MONOTONIC timeout point to the futex syscall.
Example (dummy CPP program):
``` cpp
int long_running_function() {
this_thread::sleep_for(chrono::seconds(100000)); // Simulate a long-running task
}
void timeout_function() { cout << "Timeout function executed!" << endl; }
int main(int argc, char* argv[]) {
chrono::seconds timeout_duration(2);
while (1) {
// Launch the long running function in a separate thread
future<int> result = async(launch::async, long_running_function);
// Wait for the result with a timeout
try {
if (result.wait_for(timeout_duration) == future_status::timeout) {
cout << "Long running function timed out!" << …
```
=> [DRAFT] fix: unhandled futex-related syscall

src/libfaketime.c
I noticed a bug in the semaphore handling, when using the System V semaphore
backend:
$ LD_PRELOAD=./src/libfaketime.so.1 bash -c "echo foo | sed s/foo/bar/"
libfaketime: In lock_for_stat(), ft_sem_lock failed: Invalid argument
[...exited with error...]
(Beware, the above command-line is not 100% deterministic; sometimes it
succeeds.)
Looking at the strace for the above command-line, it seems the bash echo
builtin process (or thread?) decides to remove the semaphore upon
exiting, while it's still in use by the sed process. sed then gets
EINVAL error ("Invalid argument") on its next semop call.
The root cause is a semantic difference between POSIX sem_unlink and
SysV semop(..., IPC_RMID), the two implementations for ft_sem_unlink:
* sem_unlink allows the semaphore to be used afterwards, as …
=> Only let the owner clean up semaphore and shared memory
